### ISSUE TITLE
TemplateDoesNotExist At/

### ISSUE THREAD

**Issue by swiss809** [muvatech/Shopping-Cart-Using-Django-2.0-and-Python-3.6#1]
Hi I am new to django and i keep getting this error. any advise will be greatly appreciated.

http://localhost:8000/
2.0.6
TemplateDoesNotExist
shop/product/list.html
/home/donflacko/.local/lib/python3.6/site-packages/django/template/loader.py in get_template, line 19
/usr/bin/python3
3.6.5
['/home/donflacko/projects/online_store/eccommerse',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/home/donflacko/.local/lib/python3.6/site-packages',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Sun, 1 Jul 2018 03:09:43 +0000

Django tried loading these templates, in this order:

Using engine django:

django.template.loaders.app_directories.Loader: /home/donflacko/projects/online_store/eccommerse/shop/templates/shop/product/list.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/donflacko/.local/lib/python3.6/site-packages/django/contrib/admin/templates/shop/product/list.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/donflacko/.local/lib/python3.6/site-packages/django/contrib/auth/templates/shop/product/list.html (Source does not exist)

**Comment by henrymbuguak** [comment]
Hey swiss809, great to hear you are learning django. Django uses template loader processor to find your templates and by default django will look for templates inside a folder called templates in your app. In your case django attempts to look for list.html inside shop/product/ directory but it does not exist that is why you are getting the error. In your shop app make sure you  have this directory templates/shop/product/list.html  also take a screenshot of your directories and upload here.

**Comment by swiss809** [comment]
Ok I remember I ran into that problem.m when doing the Django polls tutorial.. thanks for the help like you said I have my directories wrong. I remember how to fix it thanks.
