### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by bayaskin** [muvatech/Shopping-Cart-Using-Django-2.0-and-Python-3.6#3]
https://github.com/muvatech/Shopping-Cart-Using-Django-2.0-and-Python-3.6/blob/bebadddd1e377419724ea340413213b4b0eeaa3b/cart/templates/cart/detail.html#L41

in product.get__absolute_url double _ should be product.get_absolute_url

**Comment by henrymbuguak** [comment]
Hello bayaskin, Thank you for pointing that error out. We appreciate you time and we have made the correction.
